---
language: objective-c
sudo: false

install:
  - npm install
  - bower install
  - make full

script:
  - npm test

before_install:
  - nvm install 4.2
  - npm config set spin false
  - npm install -g bower
  - npm install phantomjs-prebuilt
