---
language: objective-c
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install
  - bower install
  - make full

script:
  - npm test

before_install:
  - npm config set spin false
  - npm install -g bower
  - npm install phantomjs-prebuilt
