---
language: objective-c
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install
  - bower install
  - make full

script:
  - npm test

before_install:
  - npm config set spin false
  - npm install -g bower
  # https://github.com/travis-ci/travis-ci/issues/3225
  - mkdir travis-phantomjs
  - wget https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
