---
language: objective-c
sudo: false

install:
  - npm install
  - bower install
  - make full

script:
  - npm test

before_install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install 4.2
  - npm config set spin false
  - npm install -g bower
  - npm install -g phantomjs-prebuilt
